### PR TITLE
Use `usersInfo` for `createUser` and `dropUser` integration tests

### LINKED ISSUE #1496: Implement `updateUser` command
### What should be done?

With passwords being stored, we should implement the basic [`updateUser ` command](https://www.mongodb.com/docs/manual/reference/command/updateUser/).

Also, in this issue, we should update _all_ integration tests to use `createUser`, `dropUser`, `dropAllUsersFromDatabase`, `usersInfo` commands instead of using `find`/`insert`/`delete`/etc on the `admin.system.users` collection.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/handler

### Definition of Done

- handler updated;
- integration/compatibility tests added/updated;
- spot refactorings done.

### PR DESCRIPTION
**Pull request by henvic**
# Description

Rely on the public API by using usersInfo to verify that createUser and dropUser works as appropriately, rather than calling internal methods using FindOne.

Closes #1496.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [ ] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by AlekSi** [comment]
> I ensured that PR title is good enough for the changelog.

That wasn't done.

> (for maintainers only) I set Reviewers ([@FerretDB/core](https://github.com/orgs/FerretDB/teams/core)), Milestone (Next), Labels, Project and project's Sprint fields.

That wasn't done.

The checklist is there to actually check yourself, not just to check items on autopilot.

**Comment by henvic** [comment]
Oops, sorry! Fixing now.

**Review by AlekSi — APPROVED** [review]

**Review by noisersup — APPROVED** [review]

**Comment by AlekSi** [comment]
The commit landed with the old subject and empty body.

**Comment by henvic** [comment]
Oops. @AlekSi, would it make sense to create a task to reset auto-merge status if PR title is changed?

**Comment by henvic** [comment]
Or maybe apply the same rules for PR title validation for the first line of the auto-merge commit?

**Comment by AlekSi** [comment]
In general, yes, but I'm not sure when and how

**Pull request merged**
