### PR TITLE
Implement $first accumulator

### LINKED ISSUE #2128: Implement `$first` accumulator
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/aggregation/first/#mongodb-group-grp.-first

`$firstN` was separated to issue https://github.com/FerretDB/FerretDB/issues/3196

DOD:
- [ ] implement first accumulator
- [ ] add integration tests for expression `{ $first: "$v" }`, `{ $first: "$v.foo" }`, `{ $first: "$missing" }`
- [ ] add integration tests for composite types `{ $first: ["$v"] }`, `{ $first: {"v": "$v"} }`
- [ ] add integration tests for scalar types `{ $first: "v" }`, `{ $first: 42}`

### PR DESCRIPTION
**Pull request by adetunjii**
Closes #2128.

## Readiness checklist
- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [ ] I ensured that PR title is good enough for the changelog.
- [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [ ] I marked all done items in this checklist.

### CODE REVIEW

**Comment by panga** [comment]
Any updates on this fix?

**Comment by adetunjii** [comment]
> Any updates on this fix?

No, none at the moment. I had to stop working on this in the meantime. This is majorly due to internal architecture considerations.

**Comment by Evengard** [comment]
Man, this is a stopper for me for now... That is sad. My app almost ran correctly xD

**Comment by AlekSi** [comment]
We are going to add support for this (and many other aggregation pipelines stages and operators) in v2 that is going to be unveiled soon

**Pull request closed without merging**
