### PR TITLE
Support `limit` parameter in delete.

### LINKED ISSUE #82: Support limit parameter for delete operations
We should support `limit: 0` for deleting all matching documents and `limit: 1` for deleting only one. Since PostgreSQL does not support `DELETE … LIMIT …`, we should instead do a subquery:
`DELETE FROM xxx WHERE _jsonb->_id IN (SELECT _jsonb->_id FROM xxx WHERE xxx LIMIT 1)`.

### PR DESCRIPTION
**Pull request by OpenSauce**
Closes #82.

### CODE REVIEW

**Comment by OpenSauce** [comment]
I've left the tests in both the msg_delete_test and handler_test as I'm not sure which is best... Could probably clean up the test cases a bit

**Comment by AlekSi** [comment]
Let's pick one place to keep the test. We can always move it later.

**Comment by OpenSauce** [comment]
> Let's pick one place to keep the test. We can always move it later.

Just reverted the handler_test... Think keeping it in a separate file is better. Although the SQL handler isn't tested that way.

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
Thanks!

**Pull request merged**
