### PR TITLE
example

### LINKED ISSUE #1539: Query `Find` does not return error on invalid value of `$size` operator
### Versions

0.6.2

### What did you do?

To attempt to add a compat test, queried `collection.Find` with negative size filter `bson.D{{"v", bson.D{{"$size", -1}}}}` on each Provider in shareddata. The scalar values do not return error.

Example:
```
test> docs =[ { _id: 'double', v: 42.13 }, { _id: 'double-whole', v: 42 }, { _id: 'double-zero', v: 0 }, { _id: 'double-max', v: 1.7976931348623157e+308 }, { _id: 'double-smallest', v: 1.7976931348623157e+308 }]  
[
  { _id: 'double', v: 42.13 },
  { _id: 'double-whole', v: 42 },
  { _id: 'double-zero', v: 0 },
  { _id: 'double-max', v: 1.7976931348623157e+308 },
  { _id: 'double-smallest', v: 1.7976931348623157e+308 }
]
test> db.foo.insertMany(docs)
{
  acknowledged: true,
  insertedIds: {
    '0': 'double',
    '1': 'double-whole',
    '2': 'double-zero',
    '3': 'double-max',
    '4': 'double-smallest'
  }
}
test>  db.foo.find({ "v": { "$size": -1 } })

test> exit
```

### What did you expect to see?

Same as compat response of `Failed to parse $size. Expected a non-negative number in: $size: -1`.

### What did you see instead?

No error.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1539.

<!--
    Write a short description to explain changes that are not mentioned in the initial issue.
    What were the reasons for those changes?
    Which decisions did you make and why?
    What else should reviewers know about your changes?
-->
Added example script and I ran it from `task mongosh` like below.
```
test> .load /mongosh/test.example.js                                                                                                                                                                               
docs = [                                                                                                                                                                                                           
    { _id: 'double', v: 42.13 },                                                                                                                                                                                   
        { _id: 'double-whole', v: 42 },
            { _id: 'double-zero', v: 0 },
                { _id: 'double-max', v: 1.7976931348623157e+308 },
                    { _id: 'double-smallest', v: 1.7976931348623157e+308 },
                        { _id: 'double-big', v: 1.1529215e+18 },
                            { _id: 'double-null', v: null },
                                ]
                                 
                                db.foo.insertMany(docs)
                                 
                                db.foo.find({ "v": { "$size": -1 } })
                                 
... 
test>   
```

## Readiness checklist

<!--
    If you want your changes to be merged quickly,
    please follow CONTRIBUTING.md.
-->

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] I ensured that the title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

### CODE REVIEW

**Comment by chilagrow** [comment]
Added script as suggested in https://github.com/FerretDB/FerretDB/issues/1539#issuecomment-1325370817 @AlekSi, @b1ron  is this what you meant?

**Comment by chilagrow** [comment]
Let me add assertion too.

**Comment by chilagrow** [comment]
I need help with adding assertion :hand:

**Comment by AlekSi** [comment]
https://gist.github.com/b1ron/cc50d4f024c9c821ce5d71aef3372e64

But then @b1ron made a better version that compare documents, not just a number of them. Please work with him on adding that.

**Comment by chilagrow** [comment]
> https://gist.github.com/b1ron/cc50d4f024c9c821ce5d71aef3372e64
> 
> But then @b1ron made a better version that compare documents, not just a number of them. Please work with him on adding that.

Woot woot :+1:

**Comment by chilagrow** [comment]
Closing it as it will be done in #1564.

**Pull request closed without merging**
