### PR TITLE
Add `shell` subcommands (`mkdir`, `rmdir`) in `envtool`

### LINKED ISSUE #2548: Implement `shell` subcommands in `envtool`
### What should be done?

We switched from Makefiles to [Taskfiles](https://taskfile.dev) for several reasons, including making things easier for contributors on Windows. Unfortunately, sometimes we need to run some Unix-specific shell commands; for example, for creating and removing directories. Let's add those commands to `envtool` to make our Taskfiles more cross-platform.

Let's add `envtool shell` subcommand with two sub-subcommands:
- `envtool shell mkdir <dir/path1> <dir/path2> ...` should create given directories using `os.MkdirAll` (similar to `mkdir -p` on Unix).
- `envtool shell rmdir <dir/path1> <file/path2> ...` should remove given directories and files using `os.RemoveAll` (similar to `rm -fr` on Unix).

The path separator should always be `/`; we should convert it to `\` on Windows if that's needed.

We should update our Taskfiles to use those commands.

### Where?

- https://github.com/FerretDB/FerretDB/blob/main/Taskfile.yml
- https://github.com/FerretDB/FerretDB/tree/main/cmd/envtool

### Definition of Done

- `envtool` updated;
- `Taskfile.yml` updated.

### PR DESCRIPTION
**Pull request by kropidlowsky**
# Description

Closes #2548.

Added implementation of `shell` subcommands: `mkdir` `rmdir`.
When errors occur they functions return combined them into one error.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

### CODE REVIEW

**Review by chilagrow — COMMENTED** [review]
Thanks for your contribution :hugs: Great work! I have a few comments

**Comment by kropidlowsky** [comment]
@chilagrow thank you! I pushed changes

**Review by chilagrow — APPROVED** [review]
Thanks for adding the test! I've run the tests against windows :hugs:

**Review by w84thesun — APPROVED** [review]
I checked on Windows. It worked like this:
```
go run .\cmd\envtool shell mkdir tmp/test
go run .\cmd\envtool shell rmdir tmp/test
```

`bin\task env-reset` also passed.

**Pull request merged**
