### PR TITLE
Use iterators for `sort`, `limit`, `skip`, and `projection`

### LINKED ISSUE #1733: Support `getMore` command
### What should be done?

https://www.mongodb.com/docs/manual/reference/command/getMore/

- [x] Do not consume all documents in `find`: #2933
- [x] Do not consume all documents in `aggregate`
- [ ] Refactor tests (https://github.com/FerretDB/FerretDB/pull/2929/files#r1246365875)

Test script: #2761

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Closes #1733.

## Readiness checklist

* [ ] I added/updated unit tests.
* [x] I added/updated integration/compatibility tests.
* [x] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [x] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by chilagrow — APPROVED** [review]
awesome change!

**Comment by AlekSi** [comment]
@chilagrow PTAL

**Review by w84thesun — APPROVED** [review]
LGTM

**Review by rumyantseva — APPROVED** [review]
I like that we have more and more consistency!

**Pull request merged**
