### PR TITLE
Add test for issue 2803

### PR DESCRIPTION
**Pull request by ujibang**
# Description

Add test case for issue #2803

### CODE REVIEW

**Review by AlekSi — COMMENTED** [review]
Please edit the existing `test.js` file instead

**Comment by AlekSi** [comment]
@ujibang this test also fails for MongoDB: https://github.com/FerretDB/FerretDB/actions/runs/5715623191/job/15488825708?pr=3136

**Comment by ujibang** [comment]
I fixed the script

It was using options `returnDocument:'after'` that is available in mongosh. with legacy mongo it is `returnNewDocument:true`

**Comment by chilagrow** [comment]
The test should pass once the fork is up to date with FerretDB/FerretDB main branch :hugs:

**Comment by AlekSi** [comment]
@ujibang could you please merge your `main` with out current `main`?

**Comment by ujibang** [comment]
> @ujibang could you please merge your `main` with out current `main`?

done

**Comment by AlekSi** [comment]
The test script passes now: https://github.com/FerretDB/FerretDB/actions/runs/5948935768/job/16138226187?pr=3136

**Pull request closed without merging**
