### PR TITLE
Do not record partial files

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Ctrl+C can be used safely now.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by rumyantseva — COMMENTED** [review]
I had a look at this PR yesterday, and as I've never worked with this part of the code, it's hard for me to understand what it fixes and why. I see now there is less probability of creating files with the same name, and things like close/sync look more accurate. But I'm not sure if I can approve without understanding. Do we have documentation/description about this part of the code or something?

**Comment by AlekSi** [comment]
When we write to files, we write bytes, not message. At any given time, file could contain a partial message. Unit/fuzzing tests, running in parallel to integration tests that create those files, might try to read partial messages and fail.

**Review by chilagrow — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
:shipit:

**Review by noisersup — APPROVED** [review]
:shipit:

**Pull request merged**
