### PR TITLE
Add tests for insertion of documents with invalid `_id` fields

### LINKED ISSUE #2804: Invalid validation for `_id` field
### FerretDB version

v1.8.0

### Backend

Any.

### Environment

Does not matter.

### What did you do?

```js
db.test.insertOne({_id: 1, v: {_id: ["foo", "bar"]}})`
```

### What did you expect to see?

```js
{ acknowledged: true, insertedId: 1 }
```

### What did you see instead?

```
MongoServerError: The '_id' value cannot be of type array
```

---

Our validation for the `_id` field incorrectly checks nested documents. Only the top-level `_id` field should be checked. See references to this issue in tests.

### PR DESCRIPTION
**Pull request by slavabobik**
# Description
Add integration tests for error cases

Closes #2804.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by slavabobik** [comment]
@rumyantseva I've added integrations tests, could you please review it? Also can you please explain a little bit more about:
https://github.com/FerretDB/FerretDB/pull/3523#discussion_r1355715661
> What else we don't have is a test case where top-level `_id` is set as a document (a valid case, but probably rate in real life), but it's rather a separate story :)

I think this is what you mean?
https://github.com/FerretDB/FerretDB/blob/ff92b037cbc35a1d0e1e3c17ae7943313a46ff5d/integration/shareddata/composites.go#L161

**Review by rumyantseva — APPROVED** [review]
LGTM!

@slavabobik my message was that we don't have any test cases where `_id` is a document. I expect some tests will need to be adjusted if we add such a case, and this is why I think it should be a separate story.

**Comment by rumyantseva** [comment]
P.S. I created an issue to illustrate and discuss my question: #3587.

**Review by chilagrow — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
