### PR TITLE
Use composite GitHub Action for Go setup. (#122)

### PR DESCRIPTION
**Pull request by klokar**
Refs #122 

Extracted Go setup and caching to separate reusable action. Input and if statement was added until fuzz is treated in the same manner.

### CODE REVIEW

**Review by AlekSi — APPROVED** [review]
That's just awesome!

**Comment by AlekSi** [comment]
@klokar Do you by any change know if that's possible to have several actions in the same repository and make `action.yml` actually work? See https://github.com/FerretDB/github-actions and https://github.com/FerretDB/dance/runs/4447027485: the `cache-key` argument seems to be ignored.

**Comment by AlekSi** [comment]
🤦 Thank you so much. I changed one job, but was debugging another. 😅

**Comment by AlekSi** [comment]
But I wonder what `required` even means there. I would expect an error when this argument is not passed, not an empty value.

**Comment by klokar** [comment]
It happens when you're doing multiple things at a time 😄 

That's weird. In docs https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputsinput_idrequired it doesn't state that it should fail when it's not present. But how would that be useful?

**Comment by AlekSi** [comment]
https://github.com/actions/runner/issues/1070

**Pull request merged**
