### PR TITLE
Migrate to `pgx/v5`

### LINKED ISSUE #1717: Migrate to `pgx/v5`
### What should be done?

We should migrate to `github.com/jackc/pgx/v5` to stay current.
See https://github.com/jackc/pgx/blob/master/CHANGELOG.md

### Where?

Everywhere.

### Definition of Done

* `github.com/jackc/pgx/v4`, `github.com/jackc/pgtype`, `github.com/jackc/pgconn`, and `github.com/jackc/pgproto3` packages should not be present in any `go.mod` files.
* Those old packages should be added to `depguard` linter configuration.

### PR DESCRIPTION
**Pull request by craigpastro**
# Description

Closes #1717.

Update pgx to v5. It was pretty straightforward, except for the changes in `internal/handlers/pg/pgdb/pool.go`. I am not sure how you would like to handle those as there is no longer a `config.ConnConfig.Logger`.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [x] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by AlekSi** [comment]
@craigpastro Please click CLA button at https://github.com/FerretDB/FerretDB/pull/2439#issuecomment-1510475190

**Review by AlekSi — APPROVED** [review]
Great, just great!

**Comment by AlekSi** [comment]
> I am not sure how you would like to handle those as there is no longer a config.ConnConfig.Logger.

That looks great to me

**Comment by AlekSi** [comment]
@chilagrow PTAL

**Review by chilagrow — APPROVED** [review]
Amazing! Thanks for updating linter as well :hugs:

**Pull request merged**
