### PR TITLE
Implement `MsgDataSize` for Tigris

### LINKED ISSUE #773: Implement `MsgDataSize` for Tigris
https://www.mongodb.com/docs/manual/reference/command/dataSize/

https://pkg.go.dev/github.com/tigrisdata/tigris-client-go@v1.0.0-alpha.22/api/server/v1#DescribeCollectionResponse

Update an existing regular integration test, do not add compat test.

### PR DESCRIPTION
**Pull request by polldo**
# Description

This PR closes #773.

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [ ] I marked all done items in this checklist.

### CODE REVIEW

**Comment by AlekSi** [comment]
@polldo You may run `task lint` locally; see our [contributing guidelines](https://github.com/FerretDB/FerretDB/blob/main/CONTRIBUTING.md#setting-up-the-development-environment)

**Comment by polldo** [comment]
Done, it should be fine now.. However shouldn't those [wsl rules](https://github.com/bombsimon/wsl/blob/v3.3.0/doc/rules.md) enforced also to the rest of the codebase ?

**Comment by AlekSi** [comment]
We intentionally enforce those and some other new checks only for new code to avoid updating the whole codebase at once

**Comment by polldo** [comment]
>We intentionally enforce those and some other new checks only for new code to avoid updating the whole codebase at once

Nice, I like your pragmatism.

>Done, it should be fine now.. 

Sorry, I forgot to `git add` a change. 
Now it **_should_** go.

**Comment by AlekSi** [comment]
Please run `task fmt lint` to reformat your code and run linters :)

**Comment by polldo** [comment]
Unfortunately `fmt` and `lint` are in conflict.
The `fmt` task generates a change that the linter refuses.

Here's the `fmt` change:
```
diff --git a/internal/handlers/tigris/msg_datasize.go b/internal/handlers/tigris/msg_datasize.go
index 8236438..0225743 100644
--- a/internal/handlers/tigris/msg_datasize.go
+++ b/internal/handlers/tigris/msg_datasize.go
@@ -55,7 +55,6 @@ func (h *Handler) MsgDataSize(ctx context.Context, msg *wire.OpMsg) (*wire.OpMsg
        started := time.Now()
        f := fetchParam{db: db, collection: collection}
        stats, err := h.fetchStats(ctx, f)
-
        if err != nil {
                return nil, lazyerrors.Error(err)
        }
```

And here the linter feedback:
```
internal/handlers/tigris/msg_datasize.go:58:2: only one cuddle assignment allowed before if statement (wsl)
        if err != nil {
        ^
```

**Comment by AlekSi** [comment]
I think it should be formatted as

```go
        started := time.Now()

        stats, err := h.fetchStats(ctx, fetchParam{db: db, collection: collection})
        if err != nil {
                return nil, lazyerrors.Error(err)
        }
```

**Comment by polldo** [comment]
@AlekSi thanks. I made few changes and now it works fine in local env.

_Trial and error is what life is about.._

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
Thank you!

**Pull request merged**
