### PR TITLE
Disable `auto_vacuum` for SQLite

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Refs #3469.

## Readiness checklist

- [x] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [x] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by noisersup — DISMISSED** [review]
:broom:

**Review by rumyantseva — APPROVED** [review]
:shipit:

**Comment by rumyantseva** [comment]
I approve as the changes look good to me, but some tests fail.

**Review by chilagrow — COMMENTED** [review]
See the failing tests https://github.com/FerretDB/FerretDB/actions/runs/6410291230/job/17403285801?pr=3496, I think auto vacuum is locking the database.

**Review by chilagrow — COMMENTED** [review]
Thanks for fixing stress test.

Something is failing with stress test https://github.com/FerretDB/FerretDB/actions/runs/6416041905/job/17419012857?pr=3496

**Comment by AlekSi** [comment]
Added that to #3409

**Review by chilagrow — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
The code looks good to me, the tests still fail though.

**Review by chilagrow — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
:shipit:

**Pull request merged**
