### PR TITLE
Provide builds for `linux/arm/v7`

### LINKED ISSUE #1376: Provide builds for `linux/arm/v7`
### Discussed in https://github.com/FerretDB/FerretDB/discussions/1266

<div type='discussions-op-text'>

<sup>Originally posted by **gocs** October 17, 2022</sup>
Is it possible to get linux/arm/v7 builds? or is there another way I can use a mongodb-like database in **raspi 3**?</div>

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Closes #1376.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by noisersup — APPROVED** [review]

**Comment by AlekSi** [comment]
@toburger see #2171

**Comment by toburger** [comment]
Sorry, I've searched through every link but couldn't find the .deb-File for the Linux ARM to download.

**Comment by AlekSi** [comment]
That's because #2171 is not done yet

**Comment by toburger** [comment]
Ah, gotcha!

**Pull request merged**
