### PR TITLE
Initial setup of `hana` handler

### PR DESCRIPTION
**Pull request by lucboj**
# Description

This is the initial setup for the `hana` handler. It only copied the files from the `dummy` handler to the `hana` handler. No real changes were made besides adding the right package name in the files and fixing linting.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [x] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — CHANGES_REQUESTED** [review]
Let's call the package `hana` because we already have references to this name.

Please also check `task lint` results.

**Comment by AlekSi** [comment]
@lucboj Please click CLA button in [this comment](https://github.com/FerretDB/FerretDB/pull/2071#issuecomment-1448587020)

**Comment by lucboj** [comment]
@AlekSi I have made your changes. 

For the next PRs, would you want us to first create issues for what we want to change?

**Comment by AlekSi** [comment]
No, no issues are necessary. But please join our community Slack

**Comment by AlekSi** [comment]
> I have made your changes.

CleanShot 2023-03-02 at 18 28 39@2x

Please click this button to re-request review

**Review by AlekSi — APPROVED** [review]

**Review by w84thesun — APPROVED** [review]

**Pull request merged**
