### PR TITLE
Fix `update` with query operator for `upsert` option

### LINKED ISSUE #2945: updateMany with filter with no result and upsert true yields errors instead of creating new document
### FerretDB version

FerretDB v1.4.0

### Backend

PostgreSQL 15.3

### Environment

Docker using ghcr.io/ferretdb/ferretdb image

### What did you do?

```
ferretdb> db.restaurant.insertOne({ "_id" : 1, "name" : "Central Perk Cafe", "violations" : 3 });
{ acknowledged: true, insertedId: 1 }
ferretdb> db.restaurant.updateMany({ "violations": { "$gt": 3 } }, { "$set": { "found": true } }, { "upsert": true } );
MongoServerError: invalid key: "$gt" (key must not start with '$' sign)

```

### What did you expect to see?

same statement executed against mongodb:
```
test> db.restaurant.insertOne({ "_id" : 1, "name" : "Central Perk Cafe", "violations" : 3 });
{ acknowledged: true, insertedId: 1 }
test> db.restaurant.updateMany({ "violations": { "$gt": 3 } }, { "$set": { "found": true } }, { "upsert": true } );
{
  acknowledged: true,
  insertedId: ObjectId("649eb3347e069bee52c272fc"),
  matchedCount: 0,
  modifiedCount: 0,
  upsertedCount: 1
}
test> db.restaurant.countDocuments()
2
```

### What did you see instead?

`MongoServerError: invalid key: "$gt" (key must not start with '$' sign)`

```
ferretdb_1  | {
ferretdb_1  |   "Checksum": 0,
ferretdb_1  |   "FlagBits": 0,
ferretdb_1  |   "Sections": [
ferretdb_1  |     {
ferretdb_1  |       "Document": {
ferretdb_1  |         "$k": [
ferretdb_1  |           "ok",
ferretdb_1  |           "errmsg",
ferretdb_1  |           "code",
ferretdb_1  |           "codeName"
ferretdb_1  |         ],
ferretdb_1  |         "ok": {
ferretdb_1  |           "$f": 0
ferretdb_1  |         },
ferretdb_1  |         "errmsg": "invalid key: \"$gt\" (key must not start with '$' sign)",
ferretdb_1  |         "code": 2,
ferretdb_1  |         "codeName": "BadValue"
ferretdb_1  |       },
ferretdb_1  |       "Kind": 0
ferretdb_1  |     }
ferretdb_1  |   ]
ferretdb_1  | }
```

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #2945.

This is not a finest implementation, it fixes the bug. I'm keeping upsert reorganisation in this issue https://github.com/FerretDB/FerretDB/issues/3040.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by chilagrow** [comment]
```
$ task test-integration-sqlite TEST_RUN='TestUpdateFieldSet|TestUpdateFieldSetUpdateManyUpsert|TestUpdateFieldSetUpdateManyNoUpsert|TestUpdateCommandUpsertErrors'
task: [test-integration-sqlite] go test -count=1 -run='TestUpdateFieldSet|TestUpdateFieldSetUpdateManyUpsert|TestUpdateFieldSetUpdateManyNoUpsert|TestUpdateCommandUpsertErrors' -timeout=35m -race=true -tags=ferretdb_debug,ferretdb_hana -shuffle=on -coverpkg=../... -coverprofile=integration-sqlite.txt . -target-backend=ferretdb-sqlite -target-tls -compat-url='mongodb://username:password@127.0.0.1:47018/?tls=true&tlsCertificateKeyFile=../build/certs/client.pem&tlsCaFile=../build/certs/rootCA-cert.pem' -disable-filter-pushdown

ok      github.com/FerretDB/FerretDB/integration        0.784s  coverage: 40.0% of statements in ../...
```

**Comment by chilagrow** [comment]
```
$ task test-integration-sqlite TEST_RUN='TestUpdateFieldSet|TestUpdateFieldSetUpdateManyUpsert|TestUpdateFieldSetUpdateManyNoUpsert|TestUpdateCommandUpsert'

task: [test-integration-sqlite] go test -count=1 -run='TestUpdateFieldSet|TestUpdateFieldSetUpdateManyUpsert|TestUpdateFieldSetUpdateManyNoUpsert|TestUpdateCommandUpsert' -timeout=35m -race=true -tags=ferretdb_debug,ferretdb_hana -shuffle=on -coverpkg=../... -coverprofile=integration-sqlite.txt . -target-backend=ferretdb-sqlite -target-tls -compat-url='mongodb://username:password@127.0.0.1:47018/?tls=true&tlsCertificateKeyFile=../build/certs/client.pem&tlsCaFile=../build/certs/rootCA-cert.pem' -disable-filter-pushdown

ok      github.com/FerretDB/FerretDB/integration        0.831s  coverage: 40.0% of statements in ../...
```

**Comment by chilagrow** [comment]
```
$ task test-integration-sqlite TEST_RUN='TestUpdateFieldSetUpdateManyUpsert|TestUpdateCommandUpsert|TestUpdateFieldCompatSetMulti'
task: [test-integration-sqlite] go test -count=1 -run='TestUpdateFieldSetUpdateManyUpsert|TestUpdateCommandUpsert|TestUpdateFieldCompatSetMulti' -timeout=35m -race=true -tags=ferretdb_debug,ferretdb_hana -shuffle=on -coverpkg=../... -coverprofile=integration-sqlite.txt . -target-backend=ferretdb-sqlite -target-tls -compat-url='mongodb://username:password@127.0.0.1:47018/?tls=true&tlsCertificateKeyFile=../build/certs/client.pem&tlsCaFile=../build/certs/rootCA-cert.pem' -disable-filter-pushdown

ok      github.com/FerretDB/FerretDB/integration        12.979s coverage: 40.0% of statements in ../...
```

**Review by noisersup — APPROVED** [review]
LGTM

**Review by rumyantseva — APPROVED** [review]
As agreed, we wanted to solve a particular issue, and this solutions looks good to me!

**Pull request merged**
