### PR TITLE
Add `FERRETDB_USERNAME` stub

### LINKED ISSUE #4245: Implement `FERRETDB_USERNAME` and `FERRETDB_PASSWORD` for Docker images
### What should be done?

After #4243, we should support creating initial user in a way similar to [postgres](https://hub.docker.com/_/postgres) and [mongo](https://hub.docker.com/_/mongo) Docker images.

---

Everything should be done already; let's check it after #4368 is merged.

### PR DESCRIPTION
**Pull request by noisersup**
# Description

Closes #4245.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [ ] I ensured that PR title is good enough for the changelog.
- [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [ ] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — COMMENTED** [review]
I think `FERRETDB_SETUP_USERNAME` is already handled by FerretDB via the usual Kong CLI

**Comment by noisersup** [comment]
> I think `FERRETDB_SETUP_USERNAME` is already handled by FerretDB via the usual Kong CLI

@AlekSi What's the goal of this issue then? It's possible to set setup username in docker already.

**Comment by AlekSi** [comment]
We should check that it works

**Comment by noisersup** [comment]
It works, I've already checked that while working on #4246. Should I write unit test for that?

**Comment by AlekSi** [comment]
No, I don't think there is a need for it

**Pull request closed without merging**
