### PR TITLE
Quick fixes for some failing tests

### PR DESCRIPTION
**Pull request by rumyantseva**
# Description

Fixes in this PR:
- Remove `t.Parrallel()` from tests that fail with exceeded context (so we have fewer parallel tests where goroutines have to wait).
- Skip flaky tests about cursors, to be fixed in #3945.

Example of a pipeline where these tests fail: https://github.com/FerretDB/FerretDB/actions/runs/9886847696/job/27307378186?pr=4450

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — APPROVED** [review]

**Review by noisersup — APPROVED** [review]

**Comment by AlekSi** [comment]
I don't think we should restart failing tests in PR that fixes failing tests.
And I found the real problem, will send a PR shortly.

**Comment by AlekSi** [comment]
#4454

**Comment by chilagrow** [comment]
Ops, I've restarted PR 
here were the failing tests https://github.com/FerretDB/FerretDB/actions/runs/9896087344/job/27338057753?pr=4453
and I'm marking it do-not-merge for now.

**Review by chilagrow — COMMENTED** [review]
See how there are failing tests

**Pull request closed without merging**
