### PR TITLE
Run query compat tests on same collection

### LINKED ISSUE #1568: Rework integration test setup and auth
### What should be done?

At the moment, we fetch flag values but each test can't assign value for the flag. Additionally `-handler` flag is used incorrectly for validator.

* Validators should be used only for target. When we run compatibility tests with target=tigris and compat=MongoDB, we get validators for `tigris` handler for both databases and then ignore MongoDB's error. In general, `-handler`'s flag value is used incorrectly. https://github.com/FerretDB/FerretDB/blob/f0ca7811ed2aae21ce5063bd3cab533d56cf6cfb/integration/setup/setup_compat.go#L131
* Integration setup uses flag's value but unable to specify flags used per test cases. Enable test cases to test authentication. https://github.com/FerretDB/FerretDB/blob/f0ca7811ed2aae21ce5063bd3cab533d56cf6cfb/integration/setup/common.go#L231
* Test different flags values of env data `TestEnvData`.
* Test different flag values of `postgresql-url` in `TestCommandsAuthenticationSASLStart` 
* Provider is compatible with both compat and target, but validator is only compatible with target. Fix this definition https://github.com/FerretDB/FerretDB/blob/62039bf08d8cb4cd19bbc39c0c75008f13e3a48c/integration/shareddata/shareddata.go#L33-L39
* pg uri used for testing is set from creating a new listener or using existing connection on port. Rework on how uri is built and used. Currently attempting all possible combinations. Probably this wouldn't help for speed. https://github.com/FerretDB/FerretDB/blob/cc7b47db1efce9c164f5922eb564ea6b7a8592ef/integration/setup/common.go#L170-L181
* Remove code like https://github.com/FerretDB/FerretDB/blob/56a2dd17b77bcb6afe1fc64b592a7985c4df15b7/integration/create_test.go#L70-L81

Keep note that maybe we may want test data per provider.
### Where?

See references to this issue in code.

DoD:
- [x] in compat test, validators are correctly applied for target but not for compat.
- [x] tests added for `TestCommandsAuthenticationSASLStart`
  - [x] authentication with PLAIN
  - [ ] authentication with invalid credential
  - [x] authentication with valid credential
- [x] uri for specific target/compat is being built.
- [x] validator is not used for compat
- [ ] address issue numbers mentioned in the code

---

- [x] rework validations in shareddata
- [x] fix `task env-data` (#2200)
- [x] fix test script

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1568.

This is one of few PR for the issue. This is aimed to speed up tests by creating collection only once for all query compat tests.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by w84thesun — APPROVED** [review]
It seems to be working faster! Thanks!

**Review by noisersup — DISMISSED** [review]
LGTM! It's much faster, I also like how we centralize all of test cases to one map, but if I understand it's temporary :) PTAL at linters

**Comment by chilagrow** [comment]
image

I see that `test-integration-tigris` has been taking about 10min with this change, which is pretty good for what it used to be like ~20min. I think the change is negligible for`test-integration-pg`.

**Review by w84thesun — APPROVED** [review]
👍

**Review by noisersup — APPROVED** [review]
:shipit:

**Pull request merged**
