### PR TITLE
Implement `MsgDBStats` for Tigris

### LINKED ISSUE #774: Implement `MsgDBStats` for Tigris
https://www.mongodb.com/docs/manual/reference/command/dbStats/

https://pkg.go.dev/github.com/tigrisdata/tigris-client-go@v1.0.0-alpha.22/api/server/v1#DescribeDatabaseResponse

Update an existing regular integration test, do not add compat test.

### PR DESCRIPTION
**Pull request by rumyantseva**
# Description

This PR closes #774

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by w84thesun — APPROVED** [review]
LGTM.

**Review by noisersup — CHANGES_REQUESTED** [review]
I don't see any implementation of [freeStorage](https://www.mongodb.com/docs/manual/reference/command/dbStats/#std-label-dbStats-freeStorage) field. Is it in the scope of this task?

**Comment by rumyantseva** [comment]
@noisersup I don't think we have it implemented for Postgres, and I believe now we need to focus on the main functionality, so freeStorage is for future, not for now.

**Review by noisersup — APPROVED** [review]
LGTM

**Review by AlekSi — APPROVED** [review]

**Pull request merged**
