### PR TITLE
Add support for `$in` operator

### LINKED ISSUE #251: Support all comparison query operators
Support all query comparison operators for all data types.

- [x] $eq
- [x] $gt
- [x] $gte
- [x] $lt
- [x] $lte
- [ ] $in
- [x] $ne
- [x] $nin

### PR DESCRIPTION
**Pull request by ribaraka**
Closes #251.

### CODE REVIEW

**Review by seeforschauer — CHANGES_REQUESTED** [review]
could you please add functionality and tests for `regex` value in `$in`? 
and also would you please add tests that `$regex` operator cannot be used inside `$in`.

**Comment by ribaraka** [comment]
> could you please add functionality and tests for `regex` value in `$in`? and also would you please add tests that `$regex` operator cannot be used inside `$in`.

Do you mean a query like this: 
```
db.values.find({
    value: {$in: [42, {$regex: /foo/}]}
})
```

**Comment by seeforschauer** [comment]
> > could you please add functionality and tests for `regex` value in `$in`? and also would you please add tests that `$regex` operator cannot be used inside `$in`.
> 
> Do you mean a query like this:
> 
> ```
> db.values.find({
>     value: {$in: [42, {$regex: /foo/}]}
> })
> ```

yes, and `db.values.find( { value: { $in: [ /^be/, /^st/ ] } } )`

**Comment by ribaraka** [comment]
Implemented a handling `$regex` operator in `$in` operator. Similar handling has been added for `$nin` operator

**Review by seeforschauer — APPROVED** [review]

**Comment by AlekSi** [comment]
Thanks!

**Pull request merged**
