### PR TITLE
Add ignoring maxTimeMS argument in count, insert, update, delete

### LINKED ISSUE #4114: Add support for `maxTimeMS` argument in `count`, `insert`, `update`, `delete`
### FerretDB version

v1.19

### Backend

PostgreSQL 13

### Environment

OS: Docker for Mac
Deployment: Docker using ghcr.io/ferretdb/ferretdb:1.19.0 image
Deployment details: Docker version 25.0.2

### What did you do?

```sh
db.survey.insertMany( [
{ "_id": 1, "results": [ { "product": "abc", "score": 10 },
{ "product": "xyz", "score": 5 } ] },
{ "_id": 2, "results": [ { "product": "abc", "score": 8 },
{ "product": "xyz", "score": 7 } ] },
{ "_id": 3, "results": [ { "product": "abc", "score": 7 },
{ "product": "xyz", "score": 8 } ] },
{ "_id": 4, "results": [ { "product": "abc", "score": 7 },
{ "product": "def", "score": 8 } ] }
] );

db.survey.find({}).maxTimeMS(100).count();
```

### What did you expect to see?

Return: `4`

In addition to `count`, all Mongo commands support `maxTimeMS`, or at least that's what Mongo Node.js driver supports (https://github.com/mongodb/node-mongodb-native/blob/v6.3.0/src/operations/command.ts#L41) so the clients are setting it.

It can be ignored in the parser for now to unblock applications using it. See https://github.com/FerretDB/FerretDB/blob/b6fd73b429749ed35ad8573cbd24719d32c85538/internal/handler/common/count.go#L24-L43
and other similar places.

### What did you see instead?

`MongoServerError: count: unknown field "maxTimeMS"` (same for insert, update, delete).

### PR DESCRIPTION
**Pull request by farit2000**
Closes #4114.

### CODE REVIEW

**Comment by chilagrow** [comment]
Could you sign CLA please https://github.com/FerretDB/FerretDB/pull/4121#issuecomment-1963053476 :hugs:

**Review by chilagrow — COMMENTED** [review]
This PR looks like it's in progress, if that's the case let's keep it as a draft PR. If something is unclear, don't hesitate to ask us questions :hugs:

**Comment by chilagrow** [comment]
> > This PR looks like it's in progress, if that's the case let's keep it as a draft PR. If something is unclear, don't hesitate to ask us questions 🤗
> 
> Why does this look like a draft? In the task it was said that for now it is necessary to make sure that maxTimeMS is not taken into account) I think that a discussion is necessary on how it should be done correctly in change operations.

Hi @farit2000, thanks for your quick response! My apologies that I've mistaken it for a draft. The issue mentioned that the error is seen for `update`. However the `update` already has the parameter ignored, I see it's not necessary to change :hugs: Thanks for your contribution!

**Review by chilagrow — APPROVED** [review]
Thanks for your contribution :hugs:

**Review by henvic — APPROVED** [review]

**Pull request merged**
