### PR TITLE
Allow dashes (`-`) in collection names

### LINKED ISSUE #1280: Allow dashes (`-`) in collection names
### What should be done?

Currently, we reject collection names with dashes (`-`). We should allow them because they are common in real-life apps.

We should update:
* [x] code;
* [x] tests;
* [ ] `testutil.CollectionName` helper;
* [x] diff tests in the dance repo;
* [x] documentation.

### PR DESCRIPTION
**Pull request by noisersup**
# Description

Closes #1280 .

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by noisersup** [comment]
We don't check for dashes inside the dance tests so I'm not sure what should we change there

**Review by AlekSi — APPROVED** [review]

**Review by rumyantseva — COMMENTED** [review]
The code looks good to me in general.
I remember, at planning, we were discussing if we should start using dashes instead of undescores in `CollectionName` testutil's handler - https://github.com/FerretDB/FerretDB/blob/74d6f833660083a9e28cebd60186ca1224f0e4d1/internal/util/testutil/db.go#L92. So, you decided not doing it?

**Comment by noisersup** [comment]
@rumyantseva I was confused about this part and thought that discussion and mention about this function was only because it **would** not work correctly. Now, I can see that the point of this change is different. Do we finally prefer using underscores there or dashes?

**Comment by rumyantseva** [comment]
@noisersup I think the idea was to have more test cases. Personally, I'm ok with either dashes or underscores.

**Review by rumyantseva — APPROVED** [review]
LGTM as everything is tested.

**Pull request merged**
