### PR TITLE
Fix failing test `TestAggregateCompatGroupDocDotNotation`

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

See https://github.com/FerretDB/FerretDB/pull/2246#issuecomment-1487999359
and failing test https://github.com/FerretDB/FerretDB/actions/runs/4550452790/jobs/8023489900

`[42]` and `42` are the same sort order, so result in compat and target may be ordered whichever is first. This PR updates provider so that it produces unique sort order of result.
## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — CHANGES_REQUESTED** [review]
I don't think we should change our test cases until the problem uncovered by them goes away.

**Comment by AlekSi** [comment]
> [42] and 42 are the same sort order, so result in compat and target may be ordered whichever is first

That should be solved by always sorting by _id at last, and not allowing arrays for _id

**Comment by chilagrow** [comment]
See the example https://github.com/FerretDB/FerretDB/pull/2246#issuecomment-1487999359, the result only has `_id` field and sorting is applied implicitly by aggregation test.

**Comment by AlekSi** [comment]
> because _id is [42]

It should not be possible to set _id to [42]. From https://www.mongodb.com/docs/manual/core/document/#field-names:

> The field name _id is reserved for use as a primary key; its value must be unique in the collection, is immutable, and may be of any type _other than an array_.

If MongoDB breaks their own documentation there, let's consider that their mistake and don't repeat it.

**Comment by chilagrow** [comment]
> 

That is unfortunately the case :cry:

**Comment by AlekSi** [comment]
Could we set a different field in that test?

**Comment by chilagrow** [comment]
If we set other field to the test, we will lose a test case capturing existing dot notation, `v.foo` is what we have now. The failing test and the `ArrayAndDocuments` were added at the same time to cover the case where `v.foo` exists in `array-document` and also `document` in this pr https://github.com/FerretDB/FerretDB/pull/2263. That's why I think updating provider is fine for this case

**Comment by AlekSi** [comment]
Please see #2316

**Review by w84thesun — APPROVED** [review]
👍

**Review by noisersup — APPROVED** [review]

**Comment by chilagrow** [comment]
Closing since this is not the way we want to handle this.

**Pull request closed without merging**
