### PR TITLE
Add filter pushdown for `_id: <string>` for SQLite

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

It is an ad-hoc filter for an important use-case that covers only the `_id` field because it can't be an array.

Refs #3235.

Closes FerretDB/dance#625.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [x] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by AlekSi** [comment]
@b1ron please test that one

**Comment by b1ron** [comment]
I am seeing an increase in performance by over two orders of magnitude. [workloadc](https://github.com/FerretDB/dance/actions/runs/6485067358/job/17610360564?pr=614#step:7:85) now completes in around 27s whereas before it just timed out.

No string pushdown took 1298.4s to read 371 records, it now takes 10s.

**Review by rumyantseva — APPROVED** [review]
:shipit:

**Review by chilagrow — APPROVED** [review]
:rocket:

**Pull request merged**
