### PR TITLE
Use our own Prettier Docker image

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

It can be used without permission problems.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by chilagrow — COMMENTED** [review]
Yeah for me it has always worked without permission change on my linux. And it seems it always works for mac. But I recall without permission change it impacted @noisersup.

CI linter is unhappy though, still using `task fmt` :see_no_evil:

**Comment by AlekSi** [comment]
The [old image](https://github.com/tmknom/dockerfiles/blob/main/prettier/Dockerfile) used a custom user that is not necessary for local development tools, but introduces permission problems in some configurations

**Review by chilagrow — APPROVED** [review]
Thanks for the explanation!

**Comment by AlekSi** [comment]
@noisersup please try it out locally

**Review by noisersup — APPROVED** [review]
All of the commands work on my machine, the older version works either and I didn't have any issues with linters. There was a contributor that had permission problems, but it seems that we already notified them LGTM

**Pull request merged**
