### PR TITLE
Aggregation stages uses iterator

### LINKED ISSUE #1889: Use iterators in aggregation pipeline stages
### What should be done?

Currently, our aggregation stages accept and return full slices of documents. We should change them to accept and return `DocumentsIterator`s instead. They should use iterators properly (like `FilterIterator`, for example) where possible. Where that's not possible, they should do the same as `SortIterator`.

### Where?

https://github.com/FerretDB/FerretDB/tree/main/internal/handlers/common/aggregations

### Definition of Done

- common handler updated;
- spot refactorings done.

### PR DESCRIPTION
**Pull request by chilagrow**
# Description

Closes #1889.

* `$group` needs to accumulate all values in the memory so it reads all document.
* `$unwind` is a bit tricky to handle array iterator, it reads all document.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by rumyantseva — CHANGES_REQUESTED** [review]
I like the implementation (it looks similar to how `FilterIterator` works), but I see quite a lot of things fail, so this PR needs some changes to make the linters and tests pass etc.

**Comment by chilagrow** [comment]
Thanks @w84thesun for fixing the linter and merging main :hugs:

**Comment by chilagrow** [comment]
> I like the implementation (it looks similar to how `FilterIterator` works), but I see quite a lot of things fail, so this PR needs some changes to make the linters and tests pass etc.

@rumyantseva thanks for noticing this, I think the failure was due to not being up to date with main branch and few conflicting change.

**Review by w84thesun — APPROVED** [review]
👍

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by noisersup — APPROVED** [review]
LGTM

**Pull request merged**
