### PR TITLE
Set default `pool_max_conns` to 20 for PostgreSQL

### LINKED ISSUE #1844: Set default `pool_max_conns=20` for PostgreSQL
### What should be done?

If `pool_max_conns` is not present in the PostgreSQL URL, assume it is 20, not pgx's default.

https://github.com/FerretDB/FerretDB/blob/d479051013c0cdd7b92469dc06eb1845c15295f9/internal/handlers/pg/pgdb/pool.go#L60

### PR DESCRIPTION
**Pull request by jkoenig134**
# Description

Closes #1844

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [x] I added/updated comments and checked rendering.
* [ ] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by jkoenig134** [comment]
@AlekSi I assumed that like setting user + password `pg.go` should be responsible for the URI manipulation and in this method I do have a `url.URL` object instead of only a string like in `pool.go`.

**Comment by AlekSi** [comment]
Here we only use per-connection username and password. All other parameters, like host, port, and all query parameters are the same.

**Comment by jkoenig134** [comment]
What about setting it in the NewOpts constructor?

**Comment by AlekSi** [comment]
Well, that's possible, but I really don't see a problem in using `u, err := url.Parse(uri)` and `uri = u.String()` in `NewPool` :) Seems to be the most natural place

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
Thank you!

**Pull request merged**
