### PR TITLE
Move handlers parameters to common

### LINKED ISSUE #2465: Refactor how we process handlers params
### What should be done?

The `internal/handlers/common` package contains code responsible for processing and validating various handlers' parameters. This code includes both generic functions such as `GetRequiredParam` and `GetOptionalParam`, as well as parameter-specific functions such as `GetSkipParam` and `GetLimitParam`. However, there are a few issues with this code.

Firstly, the **errors** returned by these functions are not adequately documented. It is unclear what these errors represent and when they should be returned. Additionally, the functions themselves lack documentation about the potential errors they may return.

Secondly, the **functions** are spread out across the entire package, making it challenging to locate and understand them.

To address these issues, significant refactoring is required. In this issue, let's create a separate package `commonparams` dedicated solely to parameter processing. This would consolidate all related code in one place and enable better documentation of both the functions and the errors they may return.

**For the scope of this issue**, the goal is to learn about parameter processing issues and send a pull request with better structuring, documentation, and possibly other improvements. 

### Where?

https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/params.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/limit.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/scale.go
https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/common/skip.go

Check other `Get*Param` functions too.

### Definition of Done

- all handlers updated;
- unit tests added/updated if needed;
- integration/compatibility tests added/updated if needed;
- spot refactorings done;
- significant refactoring are not done.

### PR DESCRIPTION
**Pull request by w84thesun**
# Description

In this PR I tried to get handlers parameters in the same way we do with `FindParams`.

Handlers moved:
* count
* delete
* explain
* insert
* update

Closes #2465.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [x] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by rumyantseva — COMMENTED** [review]
Oh, that's the exact thing I tried before, and Alexey didn't approve because there are not enough params in `count` and `delete` to move them to a common package...

**Comment by w84thesun** [comment]
> Oh, that's the exact thing I tried before, and Alexey didn't approve because there are not enough params in `count` and `delete` to move them to a common package...

Well, I guess we have to wait until Monday then...

**Review by chilagrow — APPROVED** [review]
Great!

**Comment by AlekSi** [comment]
> and Alexey didn't approve because

Because it wasn't the task your were working on. This issue is literally about moving things to the common code.

**Review by AlekSi — COMMENTED** [review]
Why we updated msg_count but not msg_delete and msg_explain for Tigris?

**Comment by w84thesun** [comment]
> Why we updated msg_count but not msg_delete and msg_explain for Tigris?

I'm on it.

**Review by rumyantseva — DISMISSED** [review]
The code looks consistent to me! Thanks for moving all these params!

**Review by rumyantseva — APPROVED** [review]

**Review by AlekSi — APPROVED** [review]

**Pull request merged**
