### PR TITLE
Make embedded FerretDB's address configurable

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

That also fixes ports conflicts when tests are run in parallel.

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [x] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by noisersup — APPROVED** [review]

**Review by w84thesun — CHANGES_REQUESTED** [review]
Integration tests are failing.

**Comment by AlekSi** [comment]
> Integration tests are failing.

That was before the last commit

**Review by w84thesun — APPROVED** [review]
LGTM

**Review by rumyantseva — APPROVED** [review]
LGTM

**Pull request merged**
