### PR TITLE
Support `$regex`'s `x` option

### LINKED ISSUE #592: Support `$regex`'s `x` option
Cover with _great_ tests and fuzzing.

### PR DESCRIPTION
**Pull request by noisersup**
Resolves #592.

### CODE REVIEW

**Comment by noisersup** [comment]
I implemented x option support. I hope that my approach meets your requirements.

I noticed that other regex options doesn't have that much of integrational tests and I'm sorry for that. They were very helpful in development process, when I didn't know exactly how would mongodb behave in some cases. I can remove some of them if needed :)

This PR also adds new unit test file [internal/types/regex_test.go](https://github.com/FerretDB/FerretDB/pull/630/files#diff-7f7f6b108eca9d5360cd367babf483bd206647f433d05495f0bae8db75812d5d) for `freeSpacingParse` and `isQuantifier` functions. I used it for testing some edge cases, which was important in regex translation. 

I'm not sure how this approach matches FerretDB workflow. If anything would be changed to make it better, let me know! I'm looking forward for review!

In the topic of fuzzing, I was looking for some examples in a codebase. I found that bson/regex is just using `fuzzBinary` for that, but I'm not sure what seed corpus should I use for this.

**Comment by noisersup** [comment]
I have added fuzzing. However, I'm not sure if that's what you are looking for @AlekSi. It just checks for panics on `freeSpacingParse`.

Let me know if there's anything I can improve!

**Review by AlekSi — COMMENTED** [review]
On hold for now

**Review by rumyantseva — COMMENTED** [review]
As it's on hold, I don't provide my review now.
Please re-request review when the task is ready.

**Comment by AlekSi** [comment]
It's dead, Jim

**Pull request closed without merging**
