### PR TITLE
Add UUID to Prometheus metrics if requested

### LINKED ISSUE #1209: Add UUID to metrics
### What should be done?

We should add UUID to Prometheus metrics to make it easier to differentiate metrics from different instances.

Let’s store it outside of the database because several instances could use the same database.

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

Closes #1209.

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [x] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by w84thesun — CHANGES_REQUESTED** [review]
Linter fails

**Comment by AlekSi** [comment]
doh, that was "last minute fix" 😆

**Review by w84thesun — APPROVED** [review]
LGTM

**Review by rumyantseva — APPROVED** [review]
LGTM

**Pull request merged**
