### PR TITLE
Allow database name contain uppercase characters

### LINKED ISSUE #2451: Allow uppercase Latin letters in database names
### What should be done?

We should allow uppercase Latin letters in a way that the backend supports it. For example, it should be possible to create database `ABC` with PostgreSQL backend, ~but then it will be the same as `abc`, `aBc`, etc~.

### Where?

* https://github.com/FerretDB/FerretDB/blob/cc34dfc541fb646579c69a692cfc90549e1ab6b7/internal/handlers/pg/pgdb/databases.go#L30-L31
* https://github.com/FerretDB/FerretDB/blob/cc34dfc541fb646579c69a692cfc90549e1ab6b7/internal/util/testutil/db.go#L66-L67
* https://github.com/FerretDB/FerretDB/blob/cc34dfc541fb646579c69a692cfc90549e1ab6b7/website/docs/diff.md?plain=1#L29

### Definition of Done

- `pgdb` tests updated;
- integration/compatibility tests updated;
- user documentation updated.

### PR DESCRIPTION
**Pull request by syasyayas**
# Description

Closes #2451.

## Readiness checklist

* [ ] I added/updated unit tests.
* [ ] I added/updated integration/compatibility tests.
* [x] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [x] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [ ] I ensured that PR title is good enough for the changelog.
* [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by syasyayas** [comment]
Checking test here because my computer dies on `task test` :)

**Comment by w84thesun** [comment]
There were a couple of places where we didn't sanitize the DB name as we should have. That's why the test are failing.
It's in internal/handlers/pg/pgdb/stats.go.
First one the line 90:
```go
	sql = `
		SELECT 
		    SUM(pg_total_relation_size(quote_ident(schemaname) || '.' || quote_ident(tablename))) 
		FROM pg_tables 
		WHERE schemaname = $1`
	args := []any{pgx.Identifier{db}.Sanitize()}
```

The second one is on line 165:
```go
		WHERE oid = '%s'::regclass`,
		pgx.Identifier{db, metadata.table}.Sanitize(),
```

Could you please fix those 2 places?

**Comment by w84thesun** [comment]
> @w84thesun, yeah sure! But what about other places like:

Thanks for noticing and handling those places!

**Review by w84thesun — DISMISSED** [review]
LGTM!

**Review by chilagrow — APPROVED** [review]
Great work!

**Review by noisersup — DISMISSED** [review]
Looks great!

**Comment by syasyayas** [comment]
I am not sure why pg tests fails... 
```
logger.go:130: 2023-04-25T08:37:56.849Z	ERROR	pgdb	tracelog/tracelog.go:335	Query	{"err": "ERROR: schema \"TestCommandsAdministrationCollStatsWithScale\" does not exist (SQLSTATE 3F000)", "time": "298.304µs", "pid": 332, "sql": "DROP SCHEMA \"TestCommandsAdministrationCollStatsWithScale\" CASCADE", "args": []}
```
I am kinda confused looking at this logs as both CreateDatabaseIfNotExists and DropDatabase in https://github.com/FerretDB/FerretDB/blob/main/internal/handlers/pg/pgdb/databases.go both sanitize db names.

**Review by w84thesun — APPROVED** [review]
LGTM!

**Review by rumyantseva — APPROVED** [review]
LGTM

**Review by ptrfarkas — APPROVED** [review]

**Comment by syasyayas** [comment]
Thanks for help!

**Comment by ptrfarkas** [comment]
@syasyayas we thank you for your valuable contribution to FerretDB!

**Pull request merged**
