### PR TITLE
Do not compare error strings

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

We are better than that.

## Readiness checklist

* [x] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Comment by AlekSi** [comment]
@rumyantseva PTAL

**Review by rumyantseva — APPROVED** [review]
It's a surprise to me that errors could be unwrapped from such deep states (but I checked locally, and it seems to be working, yes). 

LGTM

**Review by w84thesun — APPROVED** [review]

**Review by noisersup — COMMENTED** [review]
I would name the PR "Do not compare `pg` erorr string` but I'm 1 minute late to the party :)

**Comment by AlekSi** [comment]
> It's a surprise to me that errors could be unwrapped from such deep states

You are entirely correct, and that PR was utterly bogus.

> but I checked locally, and it seems to be working, yes

That's because that test (as written in #1318) is either skipped or tries to be smart and "fixes" itself in all possible combinations.

Yet both PRs were approved and merged. Why?

**Comment by AlekSi** [comment]
(my previous comment was completely wrong, deleted it)

**Pull request merged**
