### PR TITLE
Fix test names to make them more consistent

### PR DESCRIPTION
**Pull request by noisersup**
# Description

While reviewing I found out these 2 test cases starting with lowercase. I've also run a quick regex with ripgrep on whole codebase and didn't find anything else.

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [ ] I ran `task all`, and it passed.
* [ ] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [ ] I checked comments rendering with `task godocs`.
* [x] I ensured that the title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — APPROVED** [review]

**Review by AlekSi — COMMENTED** [review]
> (for maintainers only) I set Reviewers ([@FerretDB/core](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.

Not all that was done

**Comment by noisersup** [comment]
@AlekSi Yeah sorry, sprint field updated. Do we have any label for small user non-visible fixes?

**Comment by AlekSi** [comment]
Yep

**Comment by noisersup** [comment]
Noted :slightly_smiling_face:

**Review by chilagrow — APPROVED** [review]

**Review by rumyantseva — APPROVED** [review]
:shipit:

**Comment by rumyantseva** [comment]
@noisersup nice catch!

**Pull request merged**
