### PR TITLE
Add dot notation support for `$max` and `$min`

### LINKED ISSUE #1744: Update should return `WriteError` when given a bad update path
After we fix panic in #1954 / #1873, let's return correct error in this issue.

### Versions

v0.8.0

### What did you do?

This only seems to happen with `$set`, see repro in #1743.

### What did you expect to see?

```
WriteResult({
        "nMatched" : 0,
        "nUpserted" : 0,
        "nModified" : 0,
        "writeError" : {
                "code" : 56,
                "errmsg" : "The update path '0..' contains an empty field name, which is not allowed."
        }
})
```

### What did you see instead?

```
dance_ferretdb  | 2023-01-03T23:04:10.275+0545  DPANIC  // 172.29.0.1:45710 -> 172.29.0.3:27017         clientconn/conn.go:158  err must be non-nil
dance_ferretdb  | (err = <nil>)
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func2
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/clientconn/conn.go:158
dance_ferretdb  | runtime.gopanic
dance_ferretdb  |       runtime/panic.go:890
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run.func5
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/clientconn/conn.go:230
dance_ferretdb  | runtime.gopanic
dance_ferretdb  |       runtime/panic.go:890
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/types.NewPath
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/types/path.go:42
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/types.NewPathFromString
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/types/path.go:54
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/common.processSetFieldExpression
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/handlers/common/update.go:157
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/common.UpdateDocument
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/handlers/common/update.go:60
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).MsgUpdate.func2
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/handlers/pg/msg_update.go:183
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/pg/pgdb.(*Pool).InTransaction
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/handlers/pg/pgdb/transactions.go:71
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/handlers/pg.(*Handler).MsgUpdate
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/handlers/pg/msg_update.go:90
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).handleOpMsg
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/clientconn/conn.go:519
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).route
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/clientconn/conn.go:405
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.(*conn).run
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/clientconn/conn.go:294
dance_ferretdb  | github.com/FerretDB/FerretDB/internal/clientconn.acceptLoop.func1
dance_ferretdb  |       github.com/FerretDB/FerretDB/internal/clientconn/listener.go:276
dance_ferretdb  | panic: path element must not be empty
dance_ferretdb  |       panic: err must be non-nil [recovered]
dance_ferretdb  |       panic: err must be non-nil
dance_ferretdb  | (err = <nil>)
```

### Environment

```markdown
- OS: Ubuntu
- Architecture: x86_64
- Version: 22.10
- Go: go1.19.3 linux/amd64
- Git: 2.37.2
- Deployment: Docker
- Deployment details: 20.10.16
```

### DoD

- [ ] Return correct error codes, error types, if possible - messages 
- [ ] Add tests for negative path-related cases:
     - [ ] missing field in the path (`foo..`)
     - [ ] negative array indexes (`foo.-1`)
     - [ ] array indexes bigger than length (`foo.100`)
     - [ ] field doesn't exist in the path (`v.does-not-exist`) (the prefix `v` exists and is an object, part of the path doesn't exist)
     - [ ] `v.does-not-exist` where `v` exists and not an object) - compat tests should cover it as part of the previous case
     - [ ] maybe some other cases if we discover them
 - [ ] If we find new root causes for such tests to fail, we should create new issues (and skip tests)
 - [ ] Operators to cover with tests: `update` (all non-array update operators), `find` (some tests might already exist, we don't repeat them) 
 - [ ] Create a separate task to cover array update operators.

### PR DESCRIPTION
**Pull request by w84thesun**
# Description

Closes #1744.

## Readiness checklist

* [ ] I added/updated unit tests.
* [x] I added/updated integration/compatibility tests.
* [ ] I added/updated comments and checked rendering.
* [x] I made spot refactorings.
* [ ] I updated user documentation.
* [ ] I ran `task all`, and it passed.
* [x] I ensured that PR title is good enough for the changelog.
* [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Assignee, Labels, Project and project's Sprint fields.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by chilagrow — DISMISSED** [review]
Great work!

**Review by AlekSi — APPROVED** [review]

**Review by noisersup — COMMENTED** [review]
Nice catch!

Left a comment about iterator and few if err simplifications that we can approve or just omit :)

**Review by noisersup — APPROVED** [review]
LGTM :100:

**Review by rumyantseva — APPROVED** [review]
Looks reasonable to me!

**Review by chilagrow — APPROVED** [review]
Awesome work!

**Pull request merged**
