### PR TITLE
Make `task all` run only unit tests

### PR DESCRIPTION
**Pull request by AlekSi**
# Description

To make the PR template match reality.

For everyone to review.

## Readiness checklist

- [ ] I added/updated unit tests.
- [ ] I added/updated integration/compatibility tests.
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by noisersup — COMMENTED** [review]
I'm not sure if "`all`" is relevant here, as we skip the most important tests from all task "stages". Can't we leave `task all` as it is, but introduce a different task that would be also a default task?

It might be also good for us to tell contributors to use `task` in place of `task xxx` as we'll be able to just change the default task if we fix integration tests.

**Comment by AlekSi** [comment]
How to call this new target?

**Review by rumyantseva — APPROVED** [review]
LGTM

**Comment by AlekSi** [comment]
To pause Mergify for now

**Review by chilagrow — APPROVED** [review]

**Review by quasilyte — APPROVED** [review]

**Comment by quasilyte** [comment]
Yay, I've been waiting for this for two years now.

**Pull request merged**
