### PR TITLE
✨ feat: support ordered insert

### PR DESCRIPTION
**Pull request by si3nloong**
# Description

Previously, the insert statement doesn't respect `ordered` flag. After the change, it will construct a **INSERT Multiple Rows** SQL statement instead of multiple single **INSERT** statements.

This PR closes [#940](https://github.com/FerretDB/FerretDB/issues/940). 

## Readiness checklist

* [ ] I added tests for new functionality or bugfixes.
* [x] I ran `task all`, and it passed.
* [x] I added/updated comments for both exported and unexported top-level declarations (functions, types, etc).
* [x] I checked comments rendering with `task godocs`.
* [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — COMMENTED** [review]
> After the change, it will construct a INSERT Multiple Rows SQL statement instead of multiple single INSERT statements.

I'm afraid that's not how MongoDB handles ordered inserts. But let's see if we can reproduce the problem with tests. Could you please add tests similar to https://github.com/FerretDB/FerretDB/blob/main/integration/delete_compat_test.go

**Comment by si3nloong** [comment]
Screenshot 2022-09-09 at 1 38 44 PM

@AlekSi I think what you said is correct, I made some mistakes there, but I will amend it and add tests.

**Review by rumyantseva — COMMENTED** [review]
I like the idea of having tests for ordered insert. I'll take another look later.

**Comment by AlekSi** [comment]
#1673

**Pull request closed without merging**
