### PR TITLE
Enable Mermaid diagrams in Docusaurus

### LINKED ISSUE #3528: Enable Mermaid diagrams in Docusaurus
### What should be done?

https://docusaurus.io/docs/markdown-features/diagrams

So blog posts like https://blog.ferretdb.io/ferretdb-v1-10-production-ready-sqlite/ could be done with much less efforts.

### Where?

Both documentation and blog.

### Definition of Done

Plugin enabled for both documentation and blog websites.

### PR DESCRIPTION
**Pull request by sid-js**
# Description

Closes #3528.

Added Mermaid Diagrams Plugin in Configuration of Docs and Blogs of `website`

## Readiness checklist

- [x] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [x] I made spot refactorings.
- [x] I updated user documentation.
- [x] I ran `task all`, and it passed.
- [x] I ensured that PR title is good enough for the changelog.
- [x] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [x] I marked all done items in this checklist.

### CODE REVIEW

**Review by AlekSi — COMMENTED** [review]
Could you please add an example diagram somewhere to demonstrate that it works?

(it would not work because the Docusaurus dependency wasn't updated: https://github.com/FerretDB/FerretDB/actions/runs/6456277919/job/17551548074?pr=3532)

**Comment by sid-js** [comment]
> Could you please add an example diagram somewhere to demonstrate that it works?
> 
> (it would not work because the Docusaurus dependency wasn't updated: https://github.com/FerretDB/FerretDB/actions/runs/6456277919/job/17551548074?pr=3532)

I thought it was updated here : https://github.com/FerretDB/deps/commit/73ca9574661cc08525ea282487b38313b8e24c83

**Comment by AlekSi** [comment]
It was, but the tag of the Docker image wasn't updated in this PR

**Comment by AlekSi** [comment]
@sid-js Please click the CLA button in this comment: https://github.com/FerretDB/FerretDB/pull/3532#issuecomment-1752874574

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
@Fashander PTAL

**Review by Fashander — APPROVED** [review]

**Comment by AlekSi** [comment]
@sid-js Merged, thanks!

**Pull request merged**
