### PR TITLE
Implement `$first` accumulator

### LINKED ISSUE #2128: Implement `$first` accumulator
### What should be done?

https://www.mongodb.com/docs/manual/reference/operator/aggregation/first/#mongodb-group-grp.-first

`$firstN` was separated to issue https://github.com/FerretDB/FerretDB/issues/3196

DOD:
- [ ] implement first accumulator
- [ ] add integration tests for expression `{ $first: "$v" }`, `{ $first: "$v.foo" }`, `{ $first: "$missing" }`
- [ ] add integration tests for composite types `{ $first: ["$v"] }`, `{ $first: {"v": "$v"} }`
- [ ] add integration tests for scalar types `{ $first: "v" }`, `{ $first: 42}`

### PR DESCRIPTION
**Pull request by teivah**
# Description

Closes #2128.

## Readiness checklist

- [ ] I added/updated unit tests (and they pass).
- [ ] I added/updated integration/compatibility tests (and they pass).
- [ ] I added/updated comments and checked rendering.
- [ ] I made spot refactorings.
- [ ] I updated user documentation.
- [ ] I ran `task all`, and it passed.
- [ ] I ensured that PR title is good enough for the changelog.
- [ ] (for maintainers only) I set Reviewers ([`@FerretDB/core`](https://github.com/orgs/FerretDB/teams/core)), Milestone (`Next`), Labels, Project and project's Sprint fields.
- [ ] I marked all done items in this checklist.

### CODE REVIEW

**Comment by teivah** [comment]
I'm struggling to run all the tasks using `task` on my machine, it takes forever. I'd be happy to use GH CI to run everything and check my PR. Could you please first set the labels, etc. to make the `Conform PR` step passing?

**Comment by AlekSi** [comment]
@teivah Please take a moment to read CONTRIBUTING.md, specifically about leaving a comment on an issue you picking up; about running a subset of integration tests (we don't want to encourage people to develop against CI because it is much slower for everyone); and about draft PRs.

**Comment by teivah** [comment]
@AlekSi I did read it, sorry I should have mentioned it. I'm not in front of the same computer so I can give you more details tonight but I tried the following command, which was not working:

```
task test-integration-pg TEST_RUN='TestAggregateCompatFirst'
```

Was it the correct command?

**Comment by AlekSi** [comment]
Yes, it looks correct. It should not take forever, though. Please provide logs when you are back so we can debug it together.

**Comment by AlekSi** [comment]
(and please leave a comment on #2891)

**Comment by chilagrow** [comment]
> @AlekSi I did read it, sorry I should have mentioned it. I'm not in front of the same computer so I can give you more details tonight but I tried the following command, which was not working:
> 
> ```
> task test-integration-pg TEST_RUN='TestAggregateCompatFirst'
> ```
> 
> Was it the correct command?

@teivah There was a bug with `TEST_RUN` flag, thanks for identifying it. Please merge `main` branch, above command for test should work now :pray:

**Comment by teivah** [comment]
@chilagrow Thanks; I'm able to run a particular test now.

One question, though. I have done the following:

1. `task init && task env-up`
2. `task test-integration-pg TEST_RUN='TestAggregateCompatFirst'` => it fails
3. I update my code (actual code, not testing code)
4. How do I test again? Like, what's the command I need to run before running `task test-integration-pg` again? It feels like the changes I'm doing are not taken into account despite running `task env-down && task init && task env-up`.

**Comment by chilagrow** [comment]
:wave: When this is ready for review, please mark it Ready for review. That will convert draft Pull Request to normal Pull Request and notify us

**Comment by chilagrow** [comment]
> @chilagrow Thanks; I'm able to run a particular test now.
> 
> One question, though. I have done the following:
> 
> 1. `task init && task env-up`
> 2. `task test-integration-pg TEST_RUN='TestAggregateCompatFirst'` => it fails
> 3. I update my code (actual code, not testing code)
> 4. How do I test again? Like, what's the command I need to run before running `task test-integration-pg` again? It feels like the changes I'm doing are not taken into account despite running `task env-down && task init && task env-up`.

After updating actual code or test code, you can rerun `task test-integration-pg TEST_RUN='TestAggregateCompatFirst'`. No need to setup environment once it has setup and started.

As for the failing test, I see that error code returned by the implementation is different for `BadValue` test case. So that is probably what needs to be update for the test to pass :hugs: 

```
--- FAIL: TestAggregateCompatFirst/BadValue/TestAggregateCompatFirst_Doubles (0.06s)
            aggregate_documents_compat_test.go:429: Target error: (Location40234) Unrecognized pipeline stage name: "$first"
            aggregate_documents_compat_test.go:429: Compat error: (Location40324) Unrecognized pipeline stage name: '$first'
            aggregate_documents_compat_test.go:429: 
                        Error Trace:    /home/chi/go/src/github.com/chilagrow/FerretDB/integration/helpers.go:165
                                                                /home/chi/go/src/github.com/chilagrow/FerretDB/integration/helpers.go:207
                                                                /home/chi/go/src/github.com/chilagrow/FerretDB/integration/aggregate_documents_compat_test.go:142
                        Error:          Not equal: 
                                        expected: mongo.CommandError{Code:40324, Message:"Unrecognized pipeline stage name: '$first'", Labels:[]string(nil), Name:"Location40324", Wrapped:error(nil), Raw:bson.Raw(nil)}
                                        actual  : mongo.CommandError{Code:40234, Message:"Unrecognized pipeline stage name: '$first'", Labels:[]string(nil), Name:"Location40234", Wrapped:error(nil), Raw:bson.Raw(nil)}
                                        
                                        Diff:
                                        --- Expected
                                        +++ Actual
                                        @@ -1,6 +1,6 @@
                                         (mongo.CommandError) {
                                        - Code: (int32) 40324,
                                        + Code: (int32) 40234,
                                          Message: (string) (len=42) "Unrecognized pipeline stage name: '$first'",
                                          Labels: ([]string) <nil>,
                                        - Name: (string) (len=13) "Location40324",
                                        + Name: (string) (len=13) "Location40234",
                                          Wrapped: (error) <nil>,
                        Test:           TestAggregateCompatFirst/BadValue/TestAggregateCompatFirst_Doubles
            aggregate_documents_compat_test.go:429: actual message: Unrecognized pipeline stage name: "$first"
````

**Review by AlekSi — COMMENTED** [review]
Please un-draft it and re-request review once it is ready

**Comment by chilagrow** [comment]
:wave: Hi @teivah, is there any update on this?

**Comment by chilagrow** [comment]
Hello @teivah, any update? Anything we can help with?

**Comment by teivah** [comment]
Hey, sorry I lost the momentum, I had some issues in understanding what to do next. Let's close it, perhaps it can be a starting point for others.

**Pull request closed without merging**
